- contracts/ethereum-sc/contracts/Bridge.sol
- contracts/ethereum-sc/contracts/ERC20Safe.sol
- contracts/ethereum-sc/test/Bridge-test.js
- contracts/ethereum-sc/test/ERC20Safe-test.js
- Add batching support for executingTransactions
- Replay attack protection for executeBatches
- Some other small improvements (see commit messages)
> Elrond to ethereum

- bridge/elrond/client.go
- bridge/elrond/client_test.go
- bridge/eth/client.go
- bridge/eth/client_test.go
- bridge/eth/contract.go
- bridge/interface.go
- bridge/models.go
- cmd/config.toml
- cmd/main.go
- contracts/ethereum-sc/scripts/deposit-afc-to-safe.js
- go.sum
- relay/monitor.go
- relay/monitor_test.go
This will migrate from single transactions to batche.
Todo:
> Use batches instead of single transactions

- bridge/elrond/client.go
- bridge/eth/client.go
- bridge/eth/client_test.go
- relay/monitor.go
- relay/relay.go
Update logging to be more relevant.
> Improve logging

- contracts/ethereum-sc/SETUP.md
- contracts/ethereum-sc/contracts/Bridge.sol
- contracts/ethereum-sc/contracts/ERC20Safe.sol
- contracts/ethereum-sc/contracts/SharedStructs.sol
- contracts/ethereum-sc/hardhat.config.js
- contracts/ethereum-sc/scripts/deploy.js
- contracts/ethereum-sc/test/Bridge-test.js
- contracts/ethereum-sc/test/ERC20Safe-test.js
Addresses findings by Monoceros Alpha team after the audit in Jun 2021
> Audit improvements 

- bridge/elrond/client.go
- bridge/elrond/client_test.go
- cmd/main.go
- relay/relay.go
- relay/relay_test.go
Fixes https://github.com/monoceros-alpha/review-elrond-eth-bridge-2021-06/issues/31
> Leader selection issue 31

- bridge/elrond/client.go
- bridge/elrond/client_test.go
- bridge/eth/client.go
- bridge/eth/client_test.go
- bridge/interface.go
- relay/monitor.go
- relay/monitor_test.go
> Feat 29/update elrond gas limits

- bridge/elrond/client.go
- bridge/elrond/client_test.go
- go.mod
- go.sum
- updated erdgo reference to v1.0.2
> Updated erdgo reference to v1.0.2

- .gitignore
- bridge/elrond/client.go
- bridge/elrond/client_test.go
- cmd/main.go
lowered gas limit for Elrond transactions
> fixed nonce too low errors

- bridge/elrond/client.go
- bridge/interface.go
- relay/relay.go
- relay/relay_test.go
https://github.com/ElrondNetwork/elrond-eth-bridge/issues/36
> Set Relay elrondPublicAddress

- bridge/elrond/client.go
- bridge/elrond/client_test.go
Add a 10 mil buffer to the elrond gas estimates.
> [#29] Add a buffer to the elrd gas estimates

- bridge/elrond/client.go
- bridge/elrond/client_test.go
- bridge/eth/client.go
- bridge/eth/client_test.go
Apart from trying to fix the elrond low nonce issue this pr also refactors the eth client no to depend on an internal state.
> [#52] Simplify eth client implementation and elrond inc nonce improvement

- bridge/config.go
- bridge/elrond/client.go
- bridge/elrond/client_test.go
- bridge/elrond/interface.go
- bridge/elrond/mock/elrondProxyStub.go
- bridge/interface.go
- cmd/config.toml.example
- go.mod
- go.sum
- relay/relay_test.go
- integrated nonce transactions handler
> Integrated nonce transactions handler

- bridge/elrond/client.go
- integrationTests/ethToElrond/transfer_test.go
- integrationTests/mock/contracts/elrond.go
- integrationTests/mock/contracts/errors.go
- integrationTests/mock/contracts/ethereum.go
- integrationTests/mock/contracts/interface.go
- integrationTests/mock/contracts/transferRequest.go
- integrationTests/mock/tokensHolder.go
- integrationTests/testInitializer.go
- added new components and changed existing ones as to allow the eth->elrond flow to work as expected
- fixed a possible panic in ElrondClient
> ETH -> Elrond part 3

- bridge/elrond/client.go
- bridge/elrond/client_test.go
> Fixed int64 parsing in Elrond client

- bridge/elrond/client.go
- bridge/elrond/client_test.go
- bridge/eth/client.go
- bridge/eth/client_test.go
- bridge/interface.go
- ethToElrond/bridgeExecutors/ethElrondBridgeExecutor.go
- ethToElrond/bridgeExecutors/ethElrondBridgeExecutor_test.go
- integrationTests/broadcaster/broadcaster_test.go
- integrationTests/broadcaster/testscommon.go
- relay/interface.go
- relay/p2p/broadcaster.go
- relay/p2p/broadcaster_test.go
- relay/p2p/errors.go
- relay/p2p/interface.go
- relay/p2p/messages.go
- relay/p2p/relayerMessageHandler.go
- relay/p2p/relayerMessageHandler_test.go
- relay/p2p/signaturesHolder.go
- relay/p2p/signaturesHolder_test.go
- relay/relay.go
- testsCommon/bridgeMock.go
- testsCommon/bridgeStub.go
- testsCommon/broadcasterStub.go
- testsCommon/interactors/bridgeContractStub.go
- testsCommon/signatureProcessorStub.go
- added ethereum signature verification
- made the ethereum client send only maximum [quorum] number of signatures as to optimize the gas cost
> Ethereum signature verification - part 3 of the new improvements set

- bridge/eth/client.go
- bridge/eth/client_test.go
Fixed Eth client msg hash passing
> Fixed Eth client msg hash passing

- bridge/eth/client.go
- cmd/bridge/main.go
- relay/relay.go
- relay/relay_test.go
Arguments injection in relayer component preparing for integration testing
> relayer arguments injection

- integrationTests/broadcaster/broadcaster_test.go
- integrationTests/messengerWrapper.go
- integrationTests/mock/converters.go
- integrationTests/mock/elrondAccountsMock.go
- integrationTests/mock/elrondChainMock.go
- integrationTests/mock/elrondContractStateMock.go
- integrationTests/mock/ethereumChainMock.go
- integrationTests/mock/tokensRegistryMock.go
- integrationTests/testscommon.go
- added integration tests infrastructure
> Integration tests infrastructure - integration tests part 1

- relay/errors.go
- relay/relay.go
checkArgs function for ArgsRelayer
> checkArgs for ArgsRelayer

- bridge/eth/client.go
- bridge/eth/client_test.go
- bridge/eth/errors.go
- cmd/bridge/main.go
- integrationTests/relayers/elrondToEth_test.go
- integrationTests/relayers/ethToElrond_test.go
- relay/relay.go
- relay/relay_test.go
- fixed the ERC20 BalanceOf query by providing the bridge's address not the ERC20's own address
> Fixed BalanceOf query parameter

- api/groups/common_test.go
- api/groups/nodeGroup.go
- api/groups/nodeGroup_test.go
- api/shared/interface.go
- cmd/bridge/config/api.toml
- cmd/bridge/config/config.toml
- cmd/bridge/flags.go
- cmd/bridge/main.go
- config/config.go
- core/constants.go
- core/types.go
- facade/relayerFacade.go
- facade/relayerFacade_test.go
- factory/storageFactory.go
- factory/storageFactory_test.go
- integrationTests/mock/common.go
- integrationTests/relayers/elrondToEth_test.go
- integrationTests/relayers/ethToElrond_test.go
- relay/errors.go
- relay/interface.go
- relay/relay.go
- relay/relay_test.go
- status/errors.go
- status/persistence.go
- status/statusHandler.go
- status/statusHandler_test.go
- testsCommon/facade/relayerfacadeStub.go
- testsCommon/storerMock.go
- added status handler storer, defined several metrics that will be persisted
- added status list endpoint route
> Status handler storer

- priceAggregator/aggregator/binance.go
- priceAggregator/aggregator/binance_test.go
- priceAggregator/aggregator/constants.go
- priceAggregator/aggregator/converters.go
- priceAggregator/aggregator/errors.go
- priceAggregator/aggregator/httpResponseGetter.go
- priceAggregator/aggregator/httpResponseGetter_test.go
- priceAggregator/aggregator/interface.go
- testsCommon/httpResponseGetterStub.go
- price aggregator for Binance
[first PR containing the first aggregator]
> Price aggregator for binance

- bridge/config.go
- bridge/eth/client.go
- bridge/eth/client_test.go
- bridge/gasManagement/disabled/disabledGasStation.go
- bridge/gasManagement/disabled/disabledGasStation_test.go
- bridge/gasManagement/factory/gasManagementFactory_test.go
- bridge/gasManagement/gasStation.go
- bridge/gasManagement/gasStation_test.go
- bridge/interface.go
- cmd/bridge/config/config.toml
- relay/relay.go
- relay/relay_test.go
- testsCommon/gasHandlerStub.go
- refactored the gas station component to use the polling handler
> Gas station refactor

- bridge/config.go
- bridge/eth/client.go
- bridge/eth/client_test.go
- cmd/bridge/config/config.toml
- cmd/bridge/main.go
- integrationTests/relayers/elrondToEth_test.go
- integrationTests/relayers/ethToElrond_test.go
- relay/relay.go
- relay/relay_test.go
- new erc20 contract address
- safe contract balance in ERC20 instead of bridge address
> Safe contract balance in ERC20 instead of bridge address

- api/gin/webServer.go
- core/polling/pollingHandler.go
- core/types.go
- ethToElrond/bridgeExecutors/errors.go
- ethToElrond/bridgeExecutors/ethElrondBridgeExecutor.go
- ethToElrond/bridgeExecutors/ethElrondBridgeExecutor_test.go
- go.mod
- go.sum
- integrationTests/ethToElrond/stateMachineExecutor_test.go
- relay/relay.go
- stateMachine/errors.go
- stateMachine/stateMachine.go
- stateMachine/stateMachine_test.go
- testsCommon/timerMock.go
- testsCommon/timerStub.go
- replaced time.After with time.Timer in the production code
> Remove time.After from production code

- clients/batch.go
- clients/batch_test.go
- clients/ethereum/client.go
- clients/ethereum/client_test.go
- clients/ethereum/errors.go
- clients/ethereum/interface.go
- core/constants.go
- core/converters.go
- core/converters_test.go
- go.sum
- testsCommon/bridgeV2/erc20ContractsHolderStub.go
- testsCommon/bridgeV2/ethereumClientWrapperStub.go
- testsCommon/bridgeV2/tokensMapperStub.go
- added unit tests for the new Ethereum client 
- added address converter real implementation
> New ethereum client tests

- core/loggerWithIdentifier.go
- ethToElrond/v2/ethToElrond/steps/step01GetPending_test.go
Created loggerWithIdentifier which is a decorator for the logger, accepting an extra identifier which will be added to the message.
> Created loggerWithIdentifier

- factory/ethElrondBridgeComponents_test.go
Cover multiple invalid args on NewEthElrondBridgeComponents
> Tests on invalid parameters on ethElrondBridgeComponents

- factory/ethElrondBridgeComponents.go
Now using the logger with identifier implementation
> Replaced todos with loggerWithIdentifier

- ethToElrond/v2/ethToElrond/steps/semiIntegrated_test.go
Fixed small issues on semiIntegrated tests.
> Fix semiIntegrated tests

- clients/ethereum/contract/contract.go
New contract.go for ethereum client
> regenerated new contract.go

- ethToElrond/v2/bridge/bridgeExecutor.go
- ethToElrond/v2/bridge/bridgeExecutor_test.go
- ethToElrond/v2/bridge/converters.go
- fixed unified bridge & added missing functionality
> Fixed unified bridge

- ethToElrond/v2/ethToElrond/steps/semiIntegrated_test.go
- factory/ethElrondBridgeComponents.go
- integrationTests/mock/elrondContractStateMock.go
- fixed integration test & semi-integration tests
> Fixed integration test & semi-integration tests

- clients/elrond/client.go
- clients/elrond/client_test.go
- clients/elrond/dataGetter.go
- clients/elrond/dataGetter_test.go
- clients/ethereum/client.go
- clients/ethereum/client_test.go
- clients/ethereum/errors.go
- cmd/bridge/config/config.toml
- config/config.go
- ethToElrond/v2/elrondToEth/constants.go
- ethToElrond/v2/elrondToEth/steps/step06ResolveSetStatus.go
- ethToElrond/v2/ethToElrond/constants.go
- ethToElrond/v2/ethToElrond/steps/step01GetPending.go
- factory/ethElrondBridgeComponents.go
- factory/ethElrondBridgeComponents_test.go
- integrationTests/mock/elrondContractStateMock.go
- integrationTests/mock/ethereumChainMock.go
- integrationTests/relayers/common.go
- integrationTests/relayers/elrondToEth_test.go
- integrationTests/relayers/ethToElrond_test.go
- integrated elrond->eth flow
- fixed & activated integration tests
> Elrond to eth integration tests

- integrationTests/mock/elrondContractStateMock.go
- integrationTests/relayers/elrondToEth_test.go
> Fixed integration tests

- clients/elrond/client.go
- clients/elrond/errors.go
- core/converters/converters.go
- core/converters/converters_test.go
- core/types.go
Todo from elrond client for pub key converter
> Implemented todo

- clients/elrond/client.go
- clients/elrond/errors.go
- clients/errors.go
- clients/ethereum/client.go
- clients/ethereum/client_test.go
- clients/ethereum/errors.go
- core/converters/converters.go
- core/converters/converters_test.go
- factory/ethElrondBridgeComponents.go
- added error handling for Address Converter
> Error handling for Address Converter

- bridges/ethElrond/steps/elrondToEth/step01GetPending.go
- integrationTests/relayers/ethToElrond_test.go
- integration tests probable fixes
> Integration tests probable fixes

- bridges/ethElrond/bridgeExecutor.go
- bridges/ethElrond/bridgeExecutor_test.go
- bridges/ethElrond/errors.go
- cmd/bridge/config/config.toml
- core/loggerWithIdentifier.go
- fixed get batch from ethereum when an invalid batch is fetched
> Fix get batch from eth

- cmd/bridge/main.go
- factory/ethElrondBridgeComponents.go
- factory/ethElrondBridgeComponents_test.go
- integrationTests/relayers/ethToElrond_test.go
Added loop to retry broadcast join in order to avoid missing the initial connection between peers.
> Broadcast join loop

- bridges/ethElrond/bridgeExecutor.go
> Fixed prints

- api/gin/webServer.go
- clients/gasManagement/gasStation.go
- core/polling/pollingHandler.go
- factory/ethElrondBridgeComponents.go
- testsCommon/timerMock.go
- testsCommon/timerStub.go
now using time.NewTimer instead of time.After
> Refactor timer

- bridges/ethElrond/steps/ethToElrond/step03SignProposedTransfer.go
- factory/ethElrondBridgeComponents.go
- fixed one bug relating the bridge instances
> Fixed one bug relating the bridge instances

- bridges/ethElrond/topology/errors.go
- bridges/ethElrond/topology/topologyHandler.go
- bridges/ethElrond/topology/topologyHandler_test.go
- cmd/bridge/config/config.toml
- config/config.go
- factory/ethElrondBridgeComponents.go
- factory/ethElrondBridgeComponents_test.go
- integrationTests/relayers/ethToElrond_test.go
- added custom interval for leader in the topology provider
> Added custom interval for leader in the topology provider

- integrationTests/mock/elrondChainMock.go
> Added print in integration tests

- bridges/ethElrond/bridgeExecutor.go
- bridges/ethElrond/bridgeExecutor_test.go
- bridges/ethElrond/interface.go
- bridges/ethElrond/steps/elrondToEth/semiIntegrated_test.go
- bridges/ethElrond/steps/elrondToEth/step03WaitForQuorumOnTransfer.go
- bridges/ethElrond/steps/elrondToEth/step03WaitForQuorumOnTransfer_test.go
- bridges/ethElrond/steps/elrondToEth/step09WaitForQuorumOnSetStatus.go
- bridges/ethElrond/steps/elrondToEth/step09WaitForQuorumOnSetStatus_test.go
- bridges/ethElrond/steps/ethToElrond/semiIntegrated_test.go
- bridges/ethElrond/steps/ethToElrond/step04WaitForQuorum.go
- bridges/ethElrond/steps/ethToElrond/step04WaitForQuorum_test.go
- bridges/ethElrond/steps/interface.go
- clients/elrond/client.go
- clients/elrond/client_test.go
- clients/ethereum/client.go
- clients/ethereum/client_test.go
- factory/ethElrondBridgeComponents.go
- testsCommon/bridge/bridgeExecutorStub.go
- testsCommon/bridge/elrondClientStub.go
- testsCommon/bridge/ethereumClientStub.go
moved the retries logic completely to bridge executor. Fixes #204
> Refactor retries logic

- bridges/ethElrond/topology/errors.go
- bridges/ethElrond/topology/hashRandomSelector_test.go
- bridges/ethElrond/topology/topologyHandler.go
- bridges/ethElrond/topology/topologyHandler_test.go
- factory/ethElrondBridgeComponents.go
- added more prints in topology handler
> More prints in topology handler

- bridges/ethElrond/bridgeExecutor.go
- bridges/ethElrond/bridgeExecutor_test.go
- bridges/ethElrond/interface.go
- bridges/ethElrond/steps/elrondToEth/semiIntegrated_test.go
- bridges/ethElrond/steps/elrondToEth/step06ResolveSetStatus.go
- bridges/ethElrond/steps/elrondToEth/step06ResolveSetStatus_test.go
- clients/elrond/client.go
- clients/elrond/client_test.go
- testsCommon/bridge/elrondClientStub.go
- fix statuses handling + added print
- action ID prints fixes
- cleanup unused function
> Fix statuses handling

- cmd/bridge/main.go
> Removed panic in main.go

- .github/workflows/build.yml
- .github/workflows/code-coverage.yml
- .github/workflows/create_release.yml
- .github/workflows/pr-tests.yml
- cmd/bridge/main.go
> Fixed p2p configs

- clients/ethereum/client.go
- clients/ethereum/client_test.go
- cmd/bridge/config/config.toml
- cmd/bridge/main.go
- cmd/priceFeeder/config/config.toml
- cmd/priceFeeder/main.go
- config/config.go
- factory/ethElrondBridgeComponents_test.go
- go.mod
- go.sum
- integrated the new proxy implementation with finality check
- changed a return error in eth client wrapper + added unit tests
> Integrated the new proxy implementation with finality check

- cmd/bridge/config/config.toml
- cmd/bridge/main.go
- cmd/priceFeeder/config/config.toml
- config/config.go
- factory/ethElrondBridgeComponents_test.go
- go.mod
- go.sum
> New SDK release

- bridges/ethElrond/bridgeExecutor_test.go
- bridges/ethElrond/constants.go
- bridges/ethElrond/constants_test.go
- clients/elrond/client.go
- clients/elrond/client_test.go
- clients/ethereum/client.go
- clients/ethereum/client_test.go
- core/constants.go
- testsCommon/bridge/ethereumClientWrapperStub.go
- added unit tests
- minor fixes & refactor in both clients
> Unit tests + minor fixes & refactor

- .github/workflows/create_release.yml
> Added permissions for create release workflow

- bridges/ethElrond/bridgeExecutor.go
- core/messages.go
- changed uniqueness of the p2p message in order to keep less messages
> Changed uniqueness of the p2p message

- .github/workflows/build.yml
- .github/workflows/code-coverage.yml
- .github/workflows/create_release.yml
- .github/workflows/pr-tests.yml
> Rebranding fixes

- clients/gasManagement/gasStation_test.go
- fixed flaky gas station unit tests
> Fixed flaky gas station unit tests

- cmd/migration/flags.go
- cmd/migration/main.go
- executors/ethereum/migrationBatchCreator.go
- executors/ethereum/migrationBatchCreator_test.go
- added amount on the migration tool (for tests)
> Added amount on the migration tool (for tests)

- cmd/migration/main.go
- executors/ethereum/interface.go
- executors/ethereum/migrationBatchCreator.go
- executors/ethereum/migrationBatchCreator_test.go
- fixed the migration app to use the correct batch ID
> Fixed the migration app to use the correct batch ID

- executors/ethereum/errors.go
> Linter fixes

- cmd/migration/config/config-mainnet-bsc.toml
- cmd/migration/config/config-mainnet-eth.toml
- added helper configs for migration
> Added helper configs for migration

- cmd/scCallsExecutor/config/config.toml
- cmd/scCallsExecutor/flags.go
- cmd/scCallsExecutor/main.go
- config/config.go
- config/tomlConfigs_test.go
- executors/multiversx/errors.go
- executors/multiversx/module/scCallsModule.go
- executors/multiversx/module/scCallsModule_test.go
- executors/multiversx/scCallsExecutor.go
- executors/multiversx/scCallsExecutor_test.go
- integrationTests/relayers/slowTests/framework/testSetup.go
- added the possibility to define 1 or more bridge proxy smart contracts in SC call executor tool
> Added the possibility to define 1 or more bridge proxy smart contracts in SC call executor tool

- cmd/migration/config/config-mainnet-eth.toml
- cmd/migration/interface.go
- cmd/migration/main.go
- executors/ethereum/common.go
- executors/ethereum/common_test.go
- executors/ethereum/migrationBatchCreator.go
- executors/ethereum/migrationBatchCreator_test.go
- added support for all token balance
- fixed a bug when fetching the gas price
- adjusted the gas limit on Ethereum
> Migration support for all balance

- integrationTests/relayers/slowTests/common.go
- integrationTests/relayers/slowTests/edgeCases_test.go
- integrationTests/relayers/slowTests/ethToMultiversXWithChainSimulator_test.go
- integrationTests/relayers/slowTests/framework/common.go
- integrationTests/relayers/slowTests/framework/keys.go
- integrationTests/relayers/slowTests/framework/testSetup.go
- integrationTests/relayers/slowTests/framework/types.go
- integrationTests/relayers/slowTests/refundWithChainSimulator_test.go
- integrationTests/relayers/slowTests/startsFromEthereumEdgecaseFlow.go
- integrationTests/relayers/slowTests/startsFromEthereumFlow.go
- integrationTests/relayers/slowTests/startsFromMultiversxFlow.go
- refactored balance checking mechanism in e2e tests
- fixed the edge case test
> Refactored balance checking mechanism in e2e tests

- cmd/scCallsExecutor/config/config.toml
- cmd/scCallsExecutor/main.go
- config/config.go
- config/tomlConfigs_test.go
- executors/multiversx/errors.go
- executors/multiversx/interface.go
- executors/multiversx/module/scCallsModule.go
- executors/multiversx/module/scCallsModule_test.go
- executors/multiversx/scCallsExecutor.go
- executors/multiversx/scCallsExecutor_test.go
- integrationTests/relayers/slowTests/framework/testSetup.go
- testsCommon/transactionExecutorStub.go
- implemented part2 of the SC executor refactor
> Implemented part2 of the SC executor refactor
